#
# This is intended to automatically trigger a PR from staging to main when a staging PR is closed
#

name: create_main_pr

run-name: create_main_pr

on:
  pull_request: # run when a PR is merged/closed...?
    types:
      - closed
    branches:
      - 'staging' ## pw_staging  ### add other branches...
    # paths:
    #   - source/**
    #   - .github/workflows/reusable.yml
    #   - .github/workflows/*_calling.yml

permissions:
  contents: write
  pull-requests: write

jobs:
  submit-pr:
    if: github.event.pull_request.merged == true  # && !contains(github.head_ref, 'no_main') ### add this to allow option to prevent main auto-PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          write-output "Creating pull request: "
          gh pr create --base main --head '${{ github.head_ref  }}' --title "${{ github.head_ref }} - auto PR" --body "Pull Request Details:

            event_name: ${{ github.event_name }}
            head_ref:  ${{ github.head_ref }}
            sha: ${{ github.sha }}
            actor: ${{ github.actor }}
            workflow_sha: ${{ github.workflow_sha }}
            ref_name: ${{ github.ref_name }}
            path: ${{ github.path }}"

### ADD RELEVANT TARGET ENVIRONMENT...