#
# This is intended to automatically trigger a PR from staging to main when a staging PR is closed
#

name: create_main_pr

run-name: create_main_pr

on:
  pull_request: # run when a PR is merged/closed...?
    types:
      - closed
    branches:
      - 'staging'
    # paths:
    #   - source/**
    #   - .github/workflows/reusable.yml
    #   - .github/workflows/*_calling.yml

permissions:
  contents: write
  pull-requests: write

jobs:
  submit-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          signoff: false
          branch: staging
          base: main
          title: 'Auto - staging to main'
          body: |
            Update report
            - Updated with *today's* date