#
# This is intended to automatically trigger a PR from staging to main when a staging PR is closed
#

name: create_main_pr

run-name: create_main_pr

on:
  pull_request: # run when a PR is merged/closed...?
    types:
      - closed
    branches:
      - 'staging'
    # paths:
    #   - source/**
    #   - .github/workflows/reusable.yml
    #   - .github/workflows/*_calling.yml

permissions:
  contents: write
  pull-requests: write

jobs:
  submit-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          write-output "Creating pull request: "
          gh pr create --base main --head staging --title "Testing auto-env deployments" --body "Yes"