name: dev_calling
run-name: dev_calling

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'
    paths:
      - source/**
      - .github/workflows/reusable.yml
      - .github/workflows/*_calling.yml


jobs:           
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: dev
      message: this is the dev deployment