name: dev_calling
run-name: dev_calling

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'
    paths:
      - source/**
      - .github/workflows/reusable.yml
      - .github/workflows/*_calling.yml


jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: dev
      message: this is the dev deployment

  # ensure pull requests run in dev and qa before merge and run in prod...
  # deploy-qa:
  #   if: ${{ github.event_name == 'pull_request' }} && contains(needs.call-workflow.result, 'success')
  #   needs: call-workflow
  #   uses: ./.github/workflows/qa_calling.yml