name: dev_calling
run-name: dev_calling

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'
    paths:
      - source/**
      - .github/workflows/reusable.yml
      - .github/workflows/*_calling.yml


jobs:
  fail-dawg:    ### IF WE'RE GOING TO DO THIS, NEED TO HAVE A 'WAIT FOR DEV' STEP FIRST
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Status
        shell: pwsh
        run: |
          exit 1
            
  # call-workflow:
  #   uses: ./.github/workflows/reusable.yml
  #   with:
  #     environment: dev
  #     message: this is the dev deployment