name: prd_ca_calling

run-name: prd_ca_calling

on:
  # schedule:
  #   - cron: "0 0,4,8,12,16,20 * * *"

  workflow_dispatch:

  pull_request: # run when a PR is merged/closed...?
    types:
      - closed
    branches:
      - 'main'
    paths:
      - source/test_workflows/**
      - .github/workflows/ca_reusable.yml
      - .github/workflows/*_ca_calling.yml

      
jobs: 
  call-workflow: 
    # runs if event != pull request, or if the pull request head is from 'staging' and doesn't contain 'no_deploy' in title.
    if: >-
      github.event_name != 'pull_request' ||
      (
        github.event.pull_request.head == 'staging' &&
        contains( github.event.pull_request.body, 'feature_ca') &&
        ! contains( github.event.pull_request.title, '[NO_DEPLOY]' )
      )
    uses: ./.github/workflows/ca_reusable.yml
    with:
      environment: ca_prd
      message: 'this is the ca_prd deployment'