name: prd_calling
run-name: prd_calling

on:
  # schedule...

  workflow_dispatch:

  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'
  #   paths:
  #     - source/*
  #     - .github/workflows/reusable.yml
  #     - .github/workflows/*_calling.yml

permissions:
  contents: read
  actions: read

# env:
#   check_workflow_name: qa_calling

jobs: 

  # Get previous prod workflow SHA
    # if ^ !match THIS workflow SHA
      # Confirm dev/qa workflows with matching SHA succeeded
    # else
      # who cares


  call-reusable-workflow:
    # if: ( contains(needs.check-qa-deployment.result, 'success') || contains(needs.check-qa-deployment.result, 'skipped'))
    # needs: check-qa-deployment
    uses: ./.github/workflows/reusable.yml
    with:
      environment: prd
      message: this is the PRD deployment