name: prd_calling

run-name: prd_calling

on:
  # schedule:
  #   - cron: "0 0,4,8,12,16,20 * * *"

  workflow_dispatch:

  pull_request: # run when a PR is merged/closed...?
    types:
      - closed
    branches:
      - 'main'
    paths:
      - source/test_workflows/**
      - .github/workflows/reusable.yml
      - .github/workflows/*_calling.yml


permissions:
  contents: read
  actions: read


jobs: 
  call-workflow:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    uses: ./.github/workflows/reusable.yml
    with:
      environment: prd
      message: 'this is the prd deployment'