name: prd_calling
run-name: prd_calling

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

env:
  check_workflow_name: qa_calling

jobs:
  check-qa-deployment:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Check Status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          ### Need to figure out logic...
          #### if calling event == 'schedule' (workflow_dispatch to test)
          ### Get last qa_calling run... 
          ### Get last prd_calling run...
          ### if the branch SHA each references isn't the same
              ### ensure the qa_calling succeeded on its last pull_request

  
  call-reusable-workflow:
    if: ( contains(needs.check-qa-deployment.result, 'success') || contains(needs.check-qa-deployment.result, 'skipped'))
    needs: check-qa-deployment
    uses: ./.github/workflows/reusable.yml
    with:
      environment: prd
      message: this is the PRD deployment