name: prd_calling
run-name: prd_calling

on:
  workflow_dispatch:


permissions:
  contents: read
  actions: read

jobs:
  # check-qa-success:
  
  call-reusable-aworkflow:
    if: contains(github.head_ref, 'test')
    uses: ./.github/workflows/reusable.yml
    with:
      environment: prd
      message: this is the PRD deployment
