name: prd_calling
run-name: prd_calling

on:
  workflow_dispatch:

  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'
  #   paths:
  #     - source/*
  #     - .github/workflows/reusable.yml
  #     - .github/workflows/*_calling.yml

permissions:
  contents: read
  actions: read

env:
  check_workflow_name: qa_calling

jobs:
  check-qa-deployment:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Check Status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          gh 

  
  call-reusable-workflow:
    if: ( contains(needs.check-qa-deployment.result, 'success') || contains(needs.check-qa-deployment.result, 'skipped'))
    needs: check-qa-deployment
    uses: ./.github/workflows/reusable.yml
    with:
      environment: prd
      message: this is the PRD deployment