name: qa_calling

run-name: qa_calling

on:
  # schedule:
  #   - cron: "0 0,4,8,12,16,20 * * *"
  
  workflow_dispatch: # call on-demand

  pull_request:
    branches:
      - 'staging'
    paths:
      - source/test_workflows/**
      - .github/workflows/reusable.yml
      - .github/workflows/*_calling.yml


permissions:
  contents: read
  actions: read


env:
  WAIT_WORKFLOW_NAME: dev_calling.yml


jobs:
  wait:
    # if trigger = pull request, let dev finish before running QA AND pull request is not coming f/ main
    if: >-
      github.event_name == 'pull_request' &&
      github.event.pull_request.head != 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        shell: bash
        run: sleep 5s

      - name: Wait for dev
        uses: codex-/await-local-workflow-run@v1
        with:
          token: ${{ github.token }}
          workflow: ${{ env.WAIT_WORKFLOW_NAME }}
          timeout_mins: 15
          poll_interval_ms: 3000

  call-workflow:
    needs: wait
    # if not a pull request && 'wait' job !fail (if it 'skips' or 'succeeds') AND pull request is not coming f/ main
    if: >-
      ( !failure() ) &&
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.head != 'main' &&
        (!contains(github.event.pull_request.head, 'no_deploy'))
      )   
    uses: ./.github/workflows/reusable.yml
    with:
      environment: qa
      message: this is the qa deployment
          