name: qa_calling
run-name: qa_calling

on:
  # schedule:
  workflow_dispatch:

  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - source/*
      - .github/workflows/reusable.yml
      - .github/workflows/*_calling.yml


permissions:
  contents: read
  actions: read

env:
  check_workflow_name: dev_calling

jobs:
  check-dev-success:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Check Status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          gh run list -w "dev_calling"
          $output   = gh run list -w "${{ env.check_workflow_name }}" --json createdAt,displayTitle,event,headBranch,headSha,name,url,status
          $final_op = $output | ConvertFrom-Json | Sort-object -Property CreatedAt -Descending

          write-output "github.sha:"
          write-output "${{ github.sha }}"

          Write-output "workflow SHAs:  "
          $final_op | select-object name,headSha
          
          write-output "Here's the matching ones..."
          $final_op | where-object { $_.event -eq 'pull_request' -and $_.headSha -eq "${{ github.sha }}" }

  # qa... 
  # if dev PR succeeded (and SHA matches)
  # # need use GitHub Token...

  call-reusable-aworkflow:
    if: contains(github.head_ref, 'test')
    uses: ./.github/workflows/reusable.yml
    with:
      environment: qa
      message: this is the QA deployment
