name: Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      message:
        required: true
        type: string


jobs:
  output:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: display message
        shell: pwsh
        run: |
          exit 1
          # Write-output "The ${{ inputs.message }} is in ${{ inputs.environment }}"

