name: test-sparse


on:
  workflow_dispatch:

  push:
    branches:
      - main

env:
  SOURCE_DIR: source/sparse-test
  DEST_DIR: other

permissions:
  id-token: write
  contents: write
  checks: write

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true
          sparse-checkout: |
            source/sparse-test

      - name: copy files
        shell: pwsh
        run: |
          $htmlFiles    = Get-ChildItem -path ${{ env.SOURCE_DIR }} -recurse -filter *.html
          $HTMLfILES
          $htmlFiles | copy-item -destination ${{ env.DEST_DIR }} -force

          # $templateFile = Get-Content -path .\swa\template_index.html -Raw

          # build list
          # foreach ( $file in $htmlFiles ) {
          #   $line = "  <li><a href=`"$($file.FullName)`">$($file.Name)</a></li>"
          # }

      - name: Push added files
        #if: steps.changed-maester-tests-reports.outputs.any_changed == 'true'
        run: |
            git config --local user.name actions-user
            git config --local user.email "actions@github.com" 
            git fetch
            git merge 
            git add .
            git commit -m "Auto updating files"
            git push -f

      - name: file checks
        shell: pwsh
        run: |

          Get-ChildItem -path ${{ env.DEST_DIR }} -recurse

          write-output " `n--------------------------`n "