name: test-sparse


on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - sparse-test/*.html

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Run
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true
          sparse-checkout: |
            sparse-test

      - name: file checks
        shell: pwsh
        run: |
          Get-ChildItem -path .\sparse-test -recurse

          write-output " `n--------------------------`n "